"""make_user_id_and_title_non_nullable

Revision ID: c23184ad2f82
Revises: 7eb7d9561b94
Create Date: 2026-01-20 00:28:09.732980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c23184ad2f82'
down_revision: Union[str, Sequence[str], None] = '7eb7d9561b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('user_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        batch_op.alter_column('title',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('title',
                   existing_type=sa.VARCHAR(),
                   nullable=True)
        batch_op.alter_column('user_id',
                   existing_type=sa.INTEGER(),
                   nullable=True)
    # ### end Alembic commands ###
